updated the members list (as of October 11)
WebClub-NITK/old_website pull request #61
Opened 2018-10-11 10:20 UTC by prajwal27

issue 39

2018-10-11 11:27 UTC, Hrily requested changes

2018-10-11 11:27 UTC, Hrily commented on data/team.json
> +            "imageUrl": "images/posts/default.jpg"
I think we have image urls in excel sheet

2018-10-11 11:27 UTC, Hrily commented on data/team.json
> +            "name": "Adarsh Honawad"
The details of these people?

2018-10-11 12:02 UTC, prajwal27 commented on data/team.json
> +            "imageUrl": "images/posts/default.jpg"
ImageUrl is just a variable. If they have submitted it through excel sheet , then we'll be updating it weekly, else imageUrl contains the default image

2018-10-11 12:04 UTC, prajwal27 commented on data/team.json
> +            "name": "Adarsh Honawad"
These people have not yet submitted their details in the excel sheet.

2018-10-11 12:05 UTC, prajwal27 reviewed
The members' details is shown only if they have updated it in the google form.

2018-10-12 09:36 UTC, salman-bhai commented
@hrily can we link the Google Sheet and the data that we fetch from it

2018-10-12 09:39 UTC, salman-bhai commented
https://coderwall.com/p/duapqq/use-a-google-spreadsheet-as-your-json-backend

2018-10-16 04:56 UTC, salman-bhai commented
@prajwal27 any updates?

2019-02-05 16:46 UTC, closed without merging