Linking Complete...i guess
WebClub-NITK/old_website pull request #8
Opened 2016-11-26 08:07 UTC by ujdcodr

Please Work!!

2016-11-26 08:46 UTC, sigsevneo requested changes

2016-11-26 08:46 UTC, sigsevneo commented on blogs.html
> +            <h4> <a href="Lecture-Repo/slides/scilab.pdf"><span class="icon"></span>Introduction to Scilab</a> </h4>
This will look for a folder called "Lecture-Repo" within the current directory, which doesn't exist. Change the href to point to the Lecture-Repo repo. Use the full link.

Similarly, all the others.

2016-11-26 08:49 UTC, sigsevneo commented
Also, don't open new PRs unless they relate to different things. If they relate to the same topic, add the commits to the same PR.

2016-11-26 08:49 UTC, ujdcodr commented
fine

2016-11-27 02:26 UTC, ujdcodr commented
@sigsevneo any issues?

2016-11-27 11:18 UTC, adeepkit01 commented
If you are on it, try modifying the descriptions to something better

2016-11-27 11:19 UTC, ujdcodr commented
Descriptions such as??

2016-11-27 11:21 UTC, adeepkit01 commented
If they look fine to you, then it's ok, if you feel something is not clear then feel free to modify it

2016-11-27 11:24 UTC, ujdcodr commented
I meant Descriptions of what?

2016-11-27 11:24 UTC, adeepkit01 commented
The one lines currently after the links like "An Introductory tutorial on Linux and bash commands" and so

2016-11-27 11:26 UTC, ujdcodr commented
got it

2016-11-27 11:27 UTC, ujdcodr commented
one question though...how do i do it without raising a separate pull request?

2016-11-27 11:30 UTC, adeepkit01 commented
You are using GitHub GUI for making the changes, aren't you?

2016-11-27 11:49 UTC, ujdcodr commented
uh...yeah

2016-11-27 11:51 UTC, ujdcodr commented
But that i'm using only for updating single files......the whole "shifting to the Lecture-Repo" thingy i did by forking, cloning, modifying and then i pushed

2016-11-27 12:08 UTC, ujdcodr commented
fixes #6

2016-11-28 07:19 UTC, ujdcodr commented
Anything else to take care of?

On Sun, Nov 27, 2016 at 5:00 PM, Ankit Deepak <notifications@github.com>
wrote:

> You are using GitHub GUI for making the changes, aren't you?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/WebClub-NITK/WebClub-NITK.github.io/pull/8#issuecomment-263116939>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AVOONneFY1lS76pdP48deY8f4FYXvxIIks5rCWnegaJpZM4K81m5>
> .
>

2016-11-28 08:25 UTC, merged